sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with Dockerfile.dev"
  - docker build -t dragmove/react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true dragmove/react-app npm run test -- --coverage

after_success:
  - echo "success test"
