sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with Dockerfile.dev"
  - docker build -t dragmove/react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true dragmove/react-app npm run test -- --coverage

after_success:
  - echo "success test"

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-2"
  app: "dock-react-app"
  env: "Dockreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-405714360350"
  bucket_path: "dock-react-app"
  on:
    branch: main